name: Docker CI/CD

on:
  push:
    branches:
      - main  # Changes this to the branch you want to trigger the CI/CD pipeline on

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Use a Docker access token if preferred instead of password.

      - name: Build and push Docker image
        run: |
          docker build -t rajatrokde/portfolio:latest .
          docker push rajatrokde/portfolio:latest

      - name: Deploy container
        run: |
          docker stop mycontainer || true
          docker rm mycontainer || true
          docker run -d -p 80:80 --name website rajatrokde/portfolio:latest
